version: '3.9'

services:
  app:
    container_name: projetoRobusto
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "${DB_PORT}:3306"
    env_file:
      - .env
    volumes:
      - .docker/db/sql:/sql
      - .docker/db/var:/var/lib/mysql
    networks:
      - app-network

  nginx:
    build:
      context: .docker/nginx
    volumes:
      - ./app:/var/www/html:delegated
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites:/etc/nginx/sites-available
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - '${EXT_PORT}:80'
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network: 
  
